# Generated by Django 4.1.3 on 2022-12-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_comment_email_remove_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('web development', 'Web Development'), ('cyber security', 'Cyber Security'), ('design', 'Design'), ('mobile development', 'Mobile Development')], default='NULL', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
