# Generated by Django 4.1.3 on 2022-12-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
